version: "3.9"
services:
  # mongo:
  #   image: mongo:4
  #   restart: always

  mongo_db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    # volumes:
    #   - mongo_db:/data/db

  node_24game:
    build: .
    ports:
      - 5000:5000
    # environment:
    # APP_NAME: 24Game
    # PORT: 4000
    # DB_URL: mongodb://root:example@mongo_db:27017
    depends_on:
      - mongo_db
  # volumes:
  #   mongo_db: {}
