version: "3.9"
services:
  mongo_db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  node_24game:
    build: .
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      DB_CONNECTION_STRING: mongodb://root:example@mongo_db:27017
    depends_on:
      - mongo_db
